// +build ignore

// This program generates schema.go. It can be invoked by running go generate
package main

import (
	"fmt"
	"os"
	"text/template"
	"time"
)

func main() {
	fmt.Println("Volleyball Ratings GraphQL Schema Generator")
	schemaFile, err := os.Create("schema.go")
	if err != nil {
		log.Fatal(err)
	}
	defer schemaFile.Close()

	packageTemplate.Execute(schemaFile, struct {
		Timestamp time.Time
	}{
		Timestamp: time.Now(),
	})
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// {{ .Timestamp }}
package graphql

`))
