// +build ignore

// This program generates schema.go. It can be invoked by running go generate
package main

import (
	"bytes"
	"fmt"
	"go/parser"
	"go/token"
	"log"
	"os"
	"text/template"
	"time"

	"github.com/pdt256/vbratings/graphql/generator"
)

func main() {
	fmt.Println("Volleyball Ratings GraphQL Schema Generator")

	var domainRoot generator.DomainRoot

	loadDomain(&domainRoot, "../app/player.go")
	loadDomain(&domainRoot, "../app/player_rating.go")

	loadEntities(&domainRoot, "../player.go")
	loadEntities(&domainRoot, "../player_rating.go")

	var schema bytes.Buffer
	domainRoot.GraphQLSchema(&schema)

	schemaFile, err := os.Create("schema.go")
	if err != nil {
		log.Fatal(err)
	}
	defer schemaFile.Close()

	packageTemplate.Execute(schemaFile, struct {
		Timestamp time.Time
		Schema    string
	}{
		Timestamp: time.Now(),
		Schema:    schema.String(),
	})
}

func loadDomain(domainRoot *generator.DomainRoot, domainFilePath string) {
	domainFs := token.NewFileSet()
	domainNode, err := parser.ParseFile(domainFs, domainFilePath, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}
	domainRoot.Domains = append(
		domainRoot.Domains,
		generator.ParseDomain(domainNode).Domains...,
	)
}

func loadEntities(domainRoot *generator.DomainRoot, entitiesFilePath string) {
	entitiesFs := token.NewFileSet()
	entitiesNode, err := parser.ParseFile(entitiesFs, entitiesFilePath, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	domainRoot.Entities = append(
		domainRoot.Entities,
		generator.ParseEntities(entitiesNode).Entities...,
	)
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
{{ $tick := "` + "`" + `" }}
// {{ .Timestamp }}
package graphql

func schemaString() string {
	return {{ $tick }}{{ .Schema }}{{ $tick }}
}
`))
